# Site settings
title: "Alish Dipani"
email: f20160005@goa.bits-pilani.ac.in
description: "Homepage"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Computer Science Undergrad at BITS Goa. || Working on interdiscplinary applications of Artificial Intelligence in Biology and Neuroscience. || GSoC'19 student developer with Ruby Science Foundation. || Intel Student Ambassador for Artificial Intelligence."
title_image: "https://avatars0.githubusercontent.com/u/21101992?s=460&v=4"
google_analytics: "UA-140472765-1"
disqus_account: alishdipaniblog
github_repository: https://github.com/alishdipani/alishdipani.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 7

# Social usernames/URLs
twitter_username: Alu57202
github_username:  alishdipani
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/alish-dipani/
google_plus_link: 
stackoverflow_link: 
xing_link: 
facebook_link:

intelDevMesh_link: https://devmesh.intel.com/users/alish-dipani
gmail_link: f20160005@goa.bits-pilani.ac.in
CV_link : https://drive.google.com/file/d/1qSLwNRHp0uGyrPDYPRteDlYZpPczjw-d/view?usp=sharing
#kaggle_link : https://www.kaggle.com/alu57202               ADD THIS
#intel_devmesh_link:

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
