# Site settings
title: "Alish Dipani"
email: f20160005@goa.bits-pilani.ac.in
description: "Homepage"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "3rd Year Computer Science Undergrad at BITS Goa.
AI Enthusiast.
 Intel Student Ambassador for Artificial Intelligence."
title_image: "https://avatars0.githubusercontent.com/u/21101992?s=460&v=4"
google_analytics: 
#disqus_account: cartenoire
github_repository: https://github.com/alishdipani/alishdipani.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  alishdipani
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/alish-dipani/
google_plus_link: 
stackoverflow_link: 
xing_link: 
facebook_link:

intelDevMesh_link: https://devmesh.intel.com/users/alish-dipani
gmail_link: f20160005@goa.bits-pilani.ac.in
CV_link : https://drive.google.com/open?id=1n93N_m47miXbX5KnYSLxW8JbxBOlPnlo
#kaggle_link : https://www.kaggle.com/alu57202               ADD THIS
#intel_devmesh_link:

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
